field: 41926178-25cf-4a46-bb32-d2273b10d768 # Bilder mit Beschriftung
fieldLayouts:
  1a1b90a7-00c1-4201-8812-f610bf4642d4:
    tabs:
      -
        elements:
          -
            fieldUid: 97e4b741-6654-4d45-86b1-c1c3f1384072 # Bild
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 65c20188-b8f5-4251-91f2-74dfbc42177b # Legende
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  65c20188-b8f5-4251-91f2-74dfbc42177b: # Legende
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Kurzer Text: was ist auf dem Bild zu sehen?'
    name: Legende
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  97e4b741-6654-4d45-86b1-c1c3f1384072: # Bild
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bild
    instructions: ''
    name: Bild
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5db9047c-c287-453a-be92-df2dcd5f8ebe' # Sonstige Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:8f51ca4a-95b9-472a-9dcc-900adacab5e4' # Gemalte Bilder
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5db9047c-c287-453a-be92-df2dcd5f8ebe' # Sonstige Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: bildText
name: 'Bild & Text'
sortOrder: 1
