defaultPlacement: end
fieldLayouts:
  ee29852b-e5ec-4fe0-af62-552d45d1868a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: sujets
name: Sujets
siteSettings:
  9238c89c-b1ce-4b99-ae2a-359e5535abf0: # Françoise Nussbaumer
    hasUrls: true
    template: null
    uriFormat: 'sujets/{slug}'
structure:
  maxLevels: 1
  uid: ba5d321a-3b6a-494b-8660-881e0f290d61
