contentColumnType: string
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2
handle: email
instructions: ''
name: 'E-Mail Adresse'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
