contentColumnType: smallint(2)
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2
handle: latitudeDegrees
instructions: ''
name: 'Geografische Breite, Grad'
searchable: false
settings:
  decimals: 0
  defaultValue: '47'
  max: '90'
  min: '0'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
