contentColumnType: smallint(2)
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2
handle: longitudeMinutes
instructions: ''
name: 'Geografische Länge, Minuten'
searchable: false
settings:
  decimals: 0
  defaultValue: '14'
  max: '59'
  min: '0'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
