columnSuffix: null
contentColumnType: smallint(2)
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2 # Kontakt
handle: longitudeDegrees
instructions: ''
name: 'Geografische Länge, Grad'
searchable: false
settings:
  decimals: 0
  defaultValue: 8
  max: 90
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
