columnSuffix: null
contentColumnType: 'decimal(3,1)'
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2 # Kontakt
handle: longitudeSeconds
instructions: ''
name: 'Geografische Länge, Sekunden'
searchable: false
settings:
  decimals: '1'
  defaultValue: 23.2
  max: 59
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
