contentColumnType: string(255)
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2
handle: newsletterSignupLink
instructions: 'Link zu Mailchimp-Formular'
name: 'Newsletter Signup Link'
searchable: false
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
