columnSuffix: null
contentColumnType: text
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2 # Kontakt
handle: newsletterSignupText
instructions: ''
name: 'Newsletter Signup Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
