columnSuffix: null
contentColumnType: integer(10)
fieldGroup: cd7c023b-379e-4d84-bc18-6942552d3f62 # Bild-Upload
handle: picHeight
instructions: 'Höhe des Bildes in cm.'
name: Bildhöhe
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
