contentColumnType: integer(10)
fieldGroup: cd7c023b-379e-4d84-bc18-6942552d3f62
handle: picPrice
instructions: ''
name: Preis
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
