contentColumnType: integer(10)
fieldGroup: cd7c023b-379e-4d84-bc18-6942552d3f62
handle: picWidth
instructions: 'Breite des Bildes in cm.'
name: Bildbreite
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '1'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
