contentColumnType: string(255)
fieldGroup: 54c01ac0-1683-46c4-b4f4-b5eb6c5a82d3
handle: registrationLink
instructions: 'Link zu Google Form.'
name: Anmelde-Link
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
