contentColumnType: text
fieldGroup: 5d585f0d-ff1d-4d1b-af7b-b40a6580d5e2
handle: telefon
instructions: ''
name: Telefonnummer
searchable: false
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
