fieldLayouts:
  e2a3a887-fdcc-4d14-a554-0dfa8a8caea5:
    tabs:
      -
        elements:
          -
            fieldUid: 33ba1e0e-27ed-4e87-98c4-2fe265b28a98 # E-Mail Adresse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a811d84-180f-4b1a-8325-5b2e6cde5c9f # Telefonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4597672-df7e-4d2d-bdff-b318c375df0d # Newsletter Signup Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6361c7f6-ac27-4b56-9a1e-40672a9fa45b # Newsletter Signup Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e0573c5-df31-4f11-9766-0a6ee1f5923b # Instagram Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7472aa4-499a-4433-b5d0-df11258a256b # Instagram Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57548489-3db0-49da-a89a-f22e09f1c3d4 # Geografische Breite, Grad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8fa75db6-de94-4226-9489-18443cc4388a # Geografische Breite, Minuten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 711847bc-0aab-44d8-b116-fe07895e9a8d # Geografische Breite, Sekunden
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2131dc45-e00f-40e6-9bcd-917e2ef45619 # Geografische Länge, Grad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5db78920-204b-4fa7-bbf5-453b6e735514 # Geografische Länge, Minuten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3c2d97ae-931c-407a-b4e8-efc1a4c4733b # Geografische Länge, Sekunden
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Kontakt
        sortOrder: 1
handle: contact
name: Kontakt
sortOrder: 1
